### ISSUE TITLE
Links are not clickable

### ISSUE THREAD

**Issue by vaibhavsingh97** [vaibhavsingh97/OpenSourceSession#2]
**Description:**
Right now links in `Admin` not clickable

**Actual Beahviour**
![image](https://user-images.githubusercontent.com/8705386/31058481-d18fc100-a6e3-11e7-876c-28995533cbde.png)

**Expected Behaviour**
Links should be clickable and when clicked should open in new tab

**Comment by skolerst** [comment]
what do you want to be clickable? the github url?

**Comment by bryanjhv** [comment]
I'd like to take this one as a Django learning.

Which links in the model should be clickable? I mean, the email can have a `mailto:[email]`, the GitHub URL, even the branch.

**Comment by vaibhavsingh97** [comment]
@skolerst @bryanjhv Both Github url and email 😄

**Comment by hawtre** [comment]
I've submitted a PR.
